### ISSUE TITLE
isEscape method is useless

### ISSUE THREAD

**Issue by felixsanz** [lechidung/escape#6]
There is no way to know if a string is escaped or not.

```ts
const matchEscHtmlRx = /["'&<>]/;

export function isEscape(str: string): boolean {
  const matchEscHtml = matchEscHtmlRx.exec(str);

  if (!matchEscHtml) {
    return false;
  }

  return true;
}
```

This will return true with a string like `foo&bar`. In fact, with text like `foo&bar is &quot;awesome&quot;` you don't know if it's escaped or not

**Comment by lechidung** [comment]
@felixsanz Thanks for your comment! Do you think option 2 is better?

Option 1: Remove `&`
```
const matchEscHtmlRx = /["'<>]/;
```

Option 2: Remove all un-escape string and check escape.
```
const matchEscHtmlRx = /["&'<>]/;
const matchUnEscRx = /&(?:amp|#38|lt|#60|gt|#62|apos|#39|quot|#34);/g;

export  function isEscape(str: string): boolean {
  const removeUnEscStr = str.replace(matchUnEscRx, "");
  const matchEscHtml = matchEscHtmlRx.exec(removeUnEscStr);

  if (!matchEscHtml) {
    return false;
  }

  return true;
}
```

**Comment by felixsanz** [comment]
I don't think so because it will be broken anyway. It's just not possible to check it so there is no point for this function (in my  honest opinion)

**Comment by lechidung** [comment]
@felixsanz 
I updated comment add **Option 2: Remove all un-escape string and check escape.** Do you think It's better?

```
const matchEscHtmlRx = /["&'<>]/;
const matchUnEscRx = /&(?:amp|#38|lt|#60|gt|#62|apos|#39|quot|#34);/g;

export  function isEscape(str: string): boolean {
  const removeUnEscStr = str.replace(matchUnEscRx, "");
  const matchEscHtml = matchEscHtmlRx.exec(removeUnEscStr);

  if (!matchEscHtml) {
    return false;
  }

  return true;
}
```

**Comment by lechidung** [comment]
@felixsanz Could you help me review result in sample code below?
https://replit.com/@lechidung/UsedOutlyingResource#index.ts

**Comment by felixsanz** [comment]
what about `isEscape("Foo&&quot;bar")` ?

**Comment by lechidung** [comment]
> "Foo&&quot;bar"

Result "Foo&&quot;bar" is true
